/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as FrontRouteImport } from './pages/front/route'
import { Route as AdminRouteImport } from './pages/admin/route'
import { Route as FrontTopicImport } from './pages/front/topic'
import { Route as FrontPhotoImport } from './pages/front/photo'
import { Route as FrontLiveImport } from './pages/front/live'
import { Route as FrontAllPhotoImport } from './pages/front/all-photo'
import { Route as AdminAdminImport } from './pages/admin/admin'
import { Route as AdminAtlasAtlasImport } from './pages/admin/atlas/atlas'

// Create/Update Routes

const FrontRouteRoute = FrontRouteImport.update({
  id: '/front',
  path: '/front',
  getParentRoute: () => rootRoute,
} as any)

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const FrontTopicRoute = FrontTopicImport.update({
  id: '/topic',
  path: '/topic',
  getParentRoute: () => FrontRouteRoute,
} as any)

const FrontPhotoRoute = FrontPhotoImport.update({
  id: '/photo',
  path: '/photo',
  getParentRoute: () => FrontRouteRoute,
} as any)

const FrontLiveRoute = FrontLiveImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => FrontRouteRoute,
} as any)

const FrontAllPhotoRoute = FrontAllPhotoImport.update({
  id: '/all-photo',
  path: '/all-photo',
  getParentRoute: () => FrontRouteRoute,
} as any)

const AdminAdminRoute = AdminAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminAtlasAtlasRoute = AdminAtlasAtlasImport.update({
  id: '/atlas/atlas',
  path: '/atlas/atlas',
  getParentRoute: () => AdminRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/front': {
      id: '/front'
      path: '/front'
      fullPath: '/front'
      preLoaderRoute: typeof FrontRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin/admin': {
      id: '/admin/admin'
      path: '/admin'
      fullPath: '/admin/admin'
      preLoaderRoute: typeof AdminAdminImport
      parentRoute: typeof AdminRouteImport
    }
    '/front/all-photo': {
      id: '/front/all-photo'
      path: '/all-photo'
      fullPath: '/front/all-photo'
      preLoaderRoute: typeof FrontAllPhotoImport
      parentRoute: typeof FrontRouteImport
    }
    '/front/live': {
      id: '/front/live'
      path: '/live'
      fullPath: '/front/live'
      preLoaderRoute: typeof FrontLiveImport
      parentRoute: typeof FrontRouteImport
    }
    '/front/photo': {
      id: '/front/photo'
      path: '/photo'
      fullPath: '/front/photo'
      preLoaderRoute: typeof FrontPhotoImport
      parentRoute: typeof FrontRouteImport
    }
    '/front/topic': {
      id: '/front/topic'
      path: '/topic'
      fullPath: '/front/topic'
      preLoaderRoute: typeof FrontTopicImport
      parentRoute: typeof FrontRouteImport
    }
    '/admin/atlas/atlas': {
      id: '/admin/atlas/atlas'
      path: '/atlas/atlas'
      fullPath: '/admin/atlas/atlas'
      preLoaderRoute: typeof AdminAtlasAtlasImport
      parentRoute: typeof AdminRouteImport
    }
  }
}

// Create and export the route tree

interface AdminRouteRouteChildren {
  AdminAdminRoute: typeof AdminAdminRoute
  AdminAtlasAtlasRoute: typeof AdminAtlasAtlasRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminRoute: AdminAdminRoute,
  AdminAtlasAtlasRoute: AdminAtlasAtlasRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface FrontRouteRouteChildren {
  FrontAllPhotoRoute: typeof FrontAllPhotoRoute
  FrontLiveRoute: typeof FrontLiveRoute
  FrontPhotoRoute: typeof FrontPhotoRoute
  FrontTopicRoute: typeof FrontTopicRoute
}

const FrontRouteRouteChildren: FrontRouteRouteChildren = {
  FrontAllPhotoRoute: FrontAllPhotoRoute,
  FrontLiveRoute: FrontLiveRoute,
  FrontPhotoRoute: FrontPhotoRoute,
  FrontTopicRoute: FrontTopicRoute,
}

const FrontRouteRouteWithChildren = FrontRouteRoute._addFileChildren(
  FrontRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/front': typeof FrontRouteRouteWithChildren
  '/admin/admin': typeof AdminAdminRoute
  '/front/all-photo': typeof FrontAllPhotoRoute
  '/front/live': typeof FrontLiveRoute
  '/front/photo': typeof FrontPhotoRoute
  '/front/topic': typeof FrontTopicRoute
  '/admin/atlas/atlas': typeof AdminAtlasAtlasRoute
}

export interface FileRoutesByTo {
  '/admin': typeof AdminRouteRouteWithChildren
  '/front': typeof FrontRouteRouteWithChildren
  '/admin/admin': typeof AdminAdminRoute
  '/front/all-photo': typeof FrontAllPhotoRoute
  '/front/live': typeof FrontLiveRoute
  '/front/photo': typeof FrontPhotoRoute
  '/front/topic': typeof FrontTopicRoute
  '/admin/atlas/atlas': typeof AdminAtlasAtlasRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/front': typeof FrontRouteRouteWithChildren
  '/admin/admin': typeof AdminAdminRoute
  '/front/all-photo': typeof FrontAllPhotoRoute
  '/front/live': typeof FrontLiveRoute
  '/front/photo': typeof FrontPhotoRoute
  '/front/topic': typeof FrontTopicRoute
  '/admin/atlas/atlas': typeof AdminAtlasAtlasRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/front'
    | '/admin/admin'
    | '/front/all-photo'
    | '/front/live'
    | '/front/photo'
    | '/front/topic'
    | '/admin/atlas/atlas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/front'
    | '/admin/admin'
    | '/front/all-photo'
    | '/front/live'
    | '/front/photo'
    | '/front/topic'
    | '/admin/atlas/atlas'
  id:
    | '__root__'
    | '/admin'
    | '/front'
    | '/admin/admin'
    | '/front/all-photo'
    | '/front/live'
    | '/front/photo'
    | '/front/topic'
    | '/admin/atlas/atlas'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  FrontRouteRoute: typeof FrontRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  FrontRouteRoute: FrontRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/admin",
        "/front"
      ]
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/admin",
        "/admin/atlas/atlas"
      ]
    },
    "/front": {
      "filePath": "front/route.tsx",
      "children": [
        "/front/all-photo",
        "/front/live",
        "/front/photo",
        "/front/topic"
      ]
    },
    "/admin/admin": {
      "filePath": "admin/admin.tsx",
      "parent": "/admin"
    },
    "/front/all-photo": {
      "filePath": "front/all-photo.tsx",
      "parent": "/front"
    },
    "/front/live": {
      "filePath": "front/live.tsx",
      "parent": "/front"
    },
    "/front/photo": {
      "filePath": "front/photo.tsx",
      "parent": "/front"
    },
    "/front/topic": {
      "filePath": "front/topic.tsx",
      "parent": "/front"
    },
    "/admin/atlas/atlas": {
      "filePath": "admin/atlas/atlas.tsx",
      "parent": "/admin"
    }
  }
}
ROUTE_MANIFEST_END */
